name: CI

on:
  push:
    branches:
      - dev
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Telegram notify (CI)
        if: always()
        run: |
          STATUS="${{ job.status }}"
          PROJECT_NAME="jetsim_api"
          BRANCH_NAME="${{ github.ref_name }}"
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")

          if [ "$STATUS" = "success" ]; then
            TEXT="Отправлены изменения по проекту - <b>${PROJECT_NAME}</b>.%0AВетка <b>${BRANCH_NAME}</b>.%0AОт <b>${COMMIT_AUTHOR}</b>.%0AКОММИТ - <b>${COMMIT_MESSAGE}</b>"
          else
            TEXT="❌ Ошибка CI по проекту - <b>${PROJECT_NAME}</b>.%0AВетка <b>${BRANCH_NAME}</b>.%0AОт <b>${COMMIT_AUTHOR}</b>.%0AКОММИТ - <b>${COMMIT_MESSAGE}</b>"
          fi

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d parse_mode=HTML \
            -d text="$TEXT"
