name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    # faqat merge bo‘lsa
    if: github.event.pull_request.merged == true

    steps:
      - name: Send Telegram message (merge only)
        run: |
          PROJECT_NAME="DAVRSMART-BACKEND-NEW-TEST"
          AUTHOR="${{ github.event.pull_request.user.login }}"
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          COMMIT_MESSAGE="${{ github.event.pull_request.title }}"

          TEXT="Отправлены изменения по проекту - davrsmart.%0AВетка ${SOURCE_BRANCH}.%0AОт ${AUTHOR}%0AКОММИТ - ${COMMIT_MESSAGE}%0A%0AЗавершен билд ${PROJECT_NAME}"

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$TEXT"
